### ISSUE TITLE
MacOSX/Linux isn't support \r

### ISSUE THREAD

**Issue by kalloc** [twskj/pretty-swag#1]
Hi.

Linux and Mac OS don't use \r in file.

> 00000000  23 21 2f 75 73 72 2f 62  69 6e 2f 65 6e 76 20 6e  |#!/usr/bin/env n|
> 00000010  6f 64 65 0d 0a                                    |ode..|           
> 00000015

**Comment by twskj** [comment]
Fixed. Thanks!
