### ISSUE TITLE
Accented characters error

### ISSUE THREAD

**Issue by khaosdoctor** [twskj/pretty-swag#12]
Error when using with accented characters (probably an utf-8 issue) like below:

![](https://i.imgur.com/GCc0WPQ.png)

**Comment by twskj** [comment]
Thanks for reporting. Can I also have a sample file to reproduce this?

**Comment by twskj** [comment]
I just updated. Can you update pretty-swag and try again?

**Comment by khaosdoctor** [comment]
Working perfectly:

![](https://i.imgur.com/Bz69RqF.png)
