### ISSUE TITLE
Feature Request: Config option to remove header

### ISSUE THREAD

**Issue by edahlseng** [twskj/pretty-swag#14]
There are some situations where it's convenient to embed the documentation into another webpage rather than display the documentation on its own. In these situations, it would be helpful if there was a config option that allows the removal of the search header.

**Comment by twskj** [comment]
Just to double check. you mean the whole navigation bar correct ?
Not just the search box.

**Comment by edahlseng** [comment]
Yeah, the whole navigation bar

**Comment by twskj** [comment]
I need to turn off filter function too because there will be no way to remove the filter after accidentally click on tags.

**Comment by twskj** [comment]
rolled out. use `-hideNav` in console.
or set `config.hideNav = true` 
Can you check?

**Comment by edahlseng** [comment]
Awesome, I'll check it out later tonight!

**Comment by edahlseng** [comment]
That's exactly it!

**Comment by twskj** [comment]
Just fyi, I changed the switch name to -noNav but still support -hideNav.
