### ISSUE TITLE
Hard to see markdown tags.

### ISSUE THREAD

**Issue by bark** [twskj/pretty-swag#17]
When using markdown and set bold the user see no difference. 
Also the code block have only small changes so it is hard to see for the user if it is a code example.

**Comment by twskj** [comment]
I updated the bold tag. I'll have a look at code block later ~~this weekend~~.

Old
![image](https://cloud.githubusercontent.com/assets/25628219/24230019/de375e62-0f4a-11e7-88fd-fae286917e60.png)

New
![image](https://cloud.githubusercontent.com/assets/25628219/24229979/9b43e634-0f4a-11e7-9e3d-29df903e9f78.png)

**Comment by twskj** [comment]
rolled out

![image](https://cloud.githubusercontent.com/assets/25628219/24235660/585963cc-0f6c-11e7-9f36-834696ffe0c1.png)
