### ISSUE TITLE
Bug: Turning off auto tags

### ISSUE THREAD

**Issue by edahlseng** [twskj/pretty-swag#18]
Even with auto tags set to false in the config, I'm still getting tags generated

**Comment by twskj** [comment]
woops let me check.

**Comment by twskj** [comment]
rolled out. can you quickly verify?

**Comment by edahlseng** [comment]
That looks good. Though, when there are no tags, it still says "Available tags:" at the top. Is it possible to remove that when there aren't any tags?

**Comment by twskj** [comment]
rolled out :-)
