### ISSUE TITLE
Feature Request: Config option to remove "Try This Operation"

### ISSUE THREAD

**Issue by toweih** [twskj/pretty-swag#19]
Would be great if I could avoid the section "Try This Operation" by simply using a CLI-flag.

**Comment by twskj** [comment]
Do you want to remove it that section completely? or Just have it shown without clicking on "Try This Operation"?

**Comment by toweih** [comment]
Yes, completely. I want to simple-doc, without having the ease of using the api directly.
_OT: I very much appreciate your work - nicely done, thank you_

**Comment by twskj** [comment]
rolled out. Can you check? use `-noReq` switch to suppress the panel

**Comment by toweih** [comment]
v0.1.88: `-noReq` works fine. 
But `-noNav` and `-hideNav` has no effect anymore.
using
`pretty-swag -i ./service_01.yaml -o lib.html -f offline -m true -noDate -noNav -noReq`

**Comment by twskj** [comment]
I'll check that in a bit

**Comment by twskj** [comment]
rolled out. It was late last night when I coded that :p

**Comment by toweih** [comment]
v0.1.89 works like a charme! thank you!
