### ISSUE TITLE
Feature request: show object properties description

### ISSUE THREAD

**Issue by guillegette** [twskj/pretty-swag#2]
Hey there, great job with pretty-swag. Exactly what I was after. Would it be possible to show somehow the description of the schema properties? 

Thanks!

**Comment by twskj** [comment]
I'm still deciding where to put it.
- pop-over on mouse over?
- make it more like  a comment next to the row? 
```
    {
        "id": "string" /* an id of the item */
        "x" : "number" /* an X position of the cursor */ 
    }
```

- or simply put a link to the model section

**Comment by guillegette** [comment]
I would with comment next to the row, visible only if there is a
description. Is nice to get a quick overview without "extra" clicks

**Comment by twskj** [comment]
I lean toward the 2nd option too.

**Comment by twskj** [comment]
rolled out.
