### ISSUE TITLE
PUT schemas violate the right hand border

### ISSUE THREAD

**Issue by gfwellman** [twskj/pretty-swag#22]
If I have a complex schema in a GET, it renders inside some sort of container with a horizontal scrollbar.  Good!

But the same schema as the input body of a PUT doesn't render with the horizontal scrollbar.  The text is unbounded to the right, going beyond the (in this case blue) border for the whole transaction, and even beyond my browser window size.

This is both in Chrome and Edge.

Other than that, great tool!

**Comment by twskj** [comment]
I'll look into this. Thanks for reporting. :-)

**Comment by gfwellman** [comment]
If you need an example, I can create one.  I just have to strip out anything that might identify the purpose of the application :-)

**Comment by twskj** [comment]
I'll try it with generated data first. If I cannot reproduce it, I'll ask for your test data.

**Comment by twskj** [comment]
Rolled out. The bug is actually on Parameter's schema . The Respond's schema  does not overflow out of div.
Can you check and let me know if it works for your data?

**Comment by gfwellman** [comment]
Woo hoo!  Nice.  Looks good.  Thanks!
