### ISSUE TITLE
Feature Request: Collapse by default

### ISSUE THREAD

**Issue by edahlseng** [twskj/pretty-swag#24]
It could be useful to render the html in a state that's collapsed by default. Maybe there could be two levels of collapse, one where everything is collapsed, and another where specific methods are collapsed, but paths aren't?

**Comment by twskj** [comment]
I might put this into a config file.
something like
```json
{
    "collapse": {
        "path": true,
        "method": true,
        "tool":true
    }
}
````

**Comment by edahlseng** [comment]
That would be perfect!

**Comment by twskj** [comment]
Rolled out on v0.1.96.

**Comment by edahlseng** [comment]
I think I've found a bug... when passing in a config option that doesn't specify anything for the `collapse` parameter, I get the following error:

```
           api.showMe = !config.collapse.path;
                                         ^
TypeError: Cannot read property 'path' of undefined
```

Is this intentional or a bug?

**Comment by twskj** [comment]
oops I'll fix that  right now.

**Comment by twskj** [comment]
rolled out on 0.1.97. can you try it out please

**Comment by edahlseng** [comment]
Will do, I'll check it out tomorrow!

**Comment by edahlseng** [comment]
Sorry for the delay, I got carried away with work. Checked it out today, and all appears to work well!
