### ISSUE TITLE
Replace rem styles

### ISSUE THREAD

**Issue by edahlseng** [twskj/pretty-swag#25]
Is it possible to replace the rem styles used in the generated output? I'm trying to embed the documents in a shadow dom, but all of the size and positioning is off in because of the reliance on rem styles

**Comment by twskj** [comment]
Do you mind give me some sample to look at?

**Comment by twskj** [comment]
I'll look into this.

**Comment by edahlseng** [comment]
One-idea for addressing this is to provide a custom style element that doesn't rely on third party styles. I don't completely know where all of the current styles come from, but it looks like a lot of them come from other dependencies?

**Comment by twskj** [comment]
Core css is from [Materializecss](http://materializecss.com) with a few custom css I put there.
I think I can switch to em but I have to look at it first.

**Comment by twskj** [comment]
I looked at it and I think it would be best to let you customize css yourself. I'll add a section to insert a custom css.

**Comment by twskj** [comment]
Now in your config file, you can pass your css like so:
```json
{
    customCSS: "h1{font-size:3em}"    
}
```

**Comment by twskj** [comment]
does it help?

**Comment by twskj** [comment]
I'll close it for now until I hear back from you.

**Comment by edahlseng** [comment]
Sorry for the delay, I was away for a couple weeks. This works well!
