### ISSUE TITLE
Crashes on improperly formatted YAML

### ISSUE THREAD

**Issue by edahlseng** [twskj/pretty-swag#27]
When attempting to parse improperly formatted YAML, pretty-swag crashes instead of returning an error in the callback. This can be tested by attempting to generate output for this example:

```
paths:
  "/{test}/":
      parameters:
        - $ref: "#/parameters/test"
    post:
      summary: This is a test file
```

(Side note: I know I've created several issues already today... let me know if you'd like a hand with any of them!)

**Comment by twskj** [comment]
This one should be an easy fix. I'll work on it today.
Also thanks for offering help, any PR is welcome :-)

**Comment by twskj** [comment]
rolled-out
