### ISSUE TITLE
-noReq doesn't do anything... I think.

### ISSUE THREAD

**Issue by craigmonson** [twskj/pretty-swag#31]
v 0.1.102

I'm under the assumption that the ```-noReq true``` flag will remove the **Request** section under the endpoint that requires CORS to be enabled.  I'm hoping to just skip over that section since we just want our endpoint documented nicely and simply created.

Here's the command I'm using:
```
pretty-swag -collapseMethod true -i swagger.yaml -o index.html -th blue-grey -noReq true
```

Thanks!

**Comment by twskj** [comment]
Let me check

**Comment by twskj** [comment]
Rolled out. Can you verify please

**Comment by craigmonson** [comment]
That totally fixed it.  Well done.  Thanks for the quick reply and quick fix.

This guy right here codes like a baws!!!!!
