### ISSUE TITLE
Feature Request: Optional Link to Home in navbar

### ISSUE THREAD

**Issue by craigmonson** [twskj/pretty-swag#32]
It'd be great if we could get an optional link to "home" button in the upper left hand corner of the navbar that we can set with a command line option.  ie: ```-home https://foo.bar.baz``` would enable your standard home icon in the upper left that linked to the input of the option.

**Comment by twskj** [comment]
Sounds like a good idea. I'll work on it this evening.

**Comment by twskj** [comment]
I might add 3 positions:
1
![image](https://user-images.githubusercontent.com/25628219/26939753-ed2b637a-4c3d-11e7-93cb-a0fe9ca9a5f9.png)

2
![image](https://user-images.githubusercontent.com/25628219/26939805-1a42a72e-4c3e-11e7-91f5-5faecd0b727c.png)

3
![image](https://user-images.githubusercontent.com/25628219/26939868-59c62290-4c3e-11e7-95de-2fd878221c4c.png)

**Comment by craigmonson** [comment]
That looks awesome. :)

**Comment by twskj** [comment]
Rolled out on v0.1.105.
Valid location values are: L, RL, RR (default to RR)
Here's an example command line

```bash
pretty-swag -i pet.json -opet.html -home.url https://github.com/twskj/pretty-swag -home.location RR -home.text myHome
```

Check it out.

**Comment by craigmonson** [comment]
LR isn't working for me, but L and RR work great!
```
Source: swagger.yaml
Dest: foo.html
Format:  singleFile
MarkDown:  Disable
Nav Bar:  Normal
Auto tags:  Enable
Initial Collapse [Path: undefined, Method: true, Tool :false]
Theme: blue-grey
No Request Panel
Home: {"URL":"/","location":"LR","text":"<font size=\"+2\">⌂</font>"}
DONE
```

**Comment by twskj** [comment]
Woops my bad. It's `RL`

**Comment by craigmonson** [comment]
That was it.  Works great!  Thanks!
