### ISSUE TITLE
Feature Request (Bug maybe?) - Include all data from the info section

### ISSUE THREAD

**Issue by craigmonson** [twskj/pretty-swag#34]
Looks like some of the data from the info section in the swagger doc is missing from the output:
  * termsOfService
  * contact
  * license

Would be great to have that included up with the version, title and description

Thanks!

**Comment by twskj** [comment]
Not a bug just a missing features :-)
I'll find time add them in.

**Comment by twskj** [comment]
Rolled out. Let me know what you think
