### ISSUE TITLE
Not compatible with NPM 5

### ISSUE THREAD

**Issue by lolobosse** [twskj/pretty-swag#38]
If you use NPM 5 you get:

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../livedoc" as it does not contain a package.json file.
```

**Comment by lolobosse** [comment]
**QUICK-FIX**:

Dowgrade to NPM 4:

```
npm install -g npm@latest-4
```

**Comment by twskj** [comment]
I'll look into this in a bit.

**Comment by twskj** [comment]
NPM 5 give me a headache when using `npm link`.
Let's wait a bit until it's settle down. I'll give it another try.

https://github.com/npm/npm/issues/16970

**Comment by twskj** [comment]
just checked with npm 5. It's all ok now.
