### ISSUE TITLE
Response types

### ISSUE THREAD

**Issue by lolobosse** [twskj/pretty-swag#39]
#As discussed in #37, it could be meaningful to offer a preview for the responses which are not human readable.

I see few use cases:

 - PDF could be displayed in `Iframes`
 - Images 🖼 
 - XML (compressed, we could prettify) 
 - JSON (compressed, we could prettify)
 - Office docs (`.odt`, `.doc`, `.csv`, `.xls`...) 📖 -> We could download them in the browser. 
 - HTML Pages (I think it is relatively common :wink:).

I have no experience with Vue.js but I think it is doable :) (even if I think that we need to modulate the template in smaller independent components 📦📦).

Let's split that in smaller issues in the relevant repo: https://github.com/twskj/livedoc 💪  

(Yeah I like smiley 😆 )

**Comment by twskj** [comment]
Messing around on this idea so I'm gonna start with this UI. 
And of course we all like smiley 😆 !!

![image](https://user-images.githubusercontent.com/25628219/28704535-b46cde8c-7330-11e7-9eab-dda2e2f76d9a.png)

**Comment by twskj** [comment]
All done :-) 
I'll roll it out sometimes this weekend.

**Comment by twskj** [comment]
Rolled out on version 0.1.115
