### ISSUE TITLE
Feature request: global header settings

### ISSUE THREAD

**Issue by guillegette** [twskj/pretty-swag#4]
While testing the API endpoints, would be great if we can define some global headers. This would be specially useful when you are setting some auth headers. 

_(sorry for all the tickets)_

**Comment by twskj** [comment]
no problem keep them coming :-)

**Comment by twskj** [comment]
I tried different interface types and ended up with this.

Thought ? comment?

![image](https://cloud.githubusercontent.com/assets/25628219/23568995/dd5422dc-0022-11e7-990d-941972732e0e.png)

**Comment by twskj** [comment]
Ideally it should slide up and down by a hot key or a button click on the nav bar.

**Comment by twskj** [comment]
rolled out.
To bring console up use  `` Ctrl + `  `` (backticks)
Available commands for now are:

- `add header -g` headerName headerValue
- `remove header -g` headerName

`tab` to auto complete is also avilable

**Comment by guillegette** [comment]
Nice one! great idea with the "console". Will try it out shortly.
