### ISSUE TITLE
File will not generate. Just hangs.

### ISSUE THREAD

**Issue by jball98** [twskj/pretty-swag#44]
Input:
pretty-swag -i swagger.json 

Output: 
Source: swagger.json
Dest: doc.html
Format:  singleFile
MarkDown:  Disable
Nav Bar:  Normal
Auto tags:  Enable
Initial Collapse [Path: false, Method: false, Tool :true]
Theme: blue

It has been stuck at this for 5 minutes. No error message at all. It works with the petstore swagger file but not mine.
Any ideas on what the problem could be?

**Comment by jball98** [comment]
After 15 minutes: Error: RangeError: Invalid string length

**Comment by twskj** [comment]
Hey what went wrong? Maybe I can make a quick fix to prevent the hang.
Let me know.

**Comment by jball98** [comment]
Took me forever to find it. I have two identical ref's in my file.
"$ref" : "#/definitions/SomeResponse"
"$ref" : "#/definitions/SomeResponse"
Swagger editor did not pick this up as an error. Is this the expected behavior in pretty-swag?

**Comment by twskj** [comment]
Pretty-swag uses [json-ref-parser](https://github.com/BigstickCarpet/json-schema-ref-parser) to resolve $ref. I think the circular $ref should be handled already. Do you have a sample I can look at?

**Comment by twskj** [comment]
I'll close this for now feel free to reopen.
