### ISSUE TITLE
Prettify json schema

### ISSUE THREAD

**Issue by jball98** [twskj/pretty-swag#45]
how can we achieve this?
like,
syntax highlighting  or json viewer instead of plain text

**Comment by twskj** [comment]
I don't have a syntax highlight on parameter schema yet but you can click on open brace and open bracket to fold/unfold the schema. I'll find time to add this in the future version

PS. the live response do have the syntax highlight and viewer when clicking preview button

**Comment by twskj** [comment]
rolled out in `0.1.152`
