### ISSUE TITLE
Properties descriptions from schema is not shown

### ISSUE THREAD

**Issue by cristianbojor** [twskj/pretty-swag#5]
Properties descriptions from schema is not shown

**Comment by cristianbojor** [comment]
When the items are in a ref

**Comment by twskj** [comment]
I'll look into it

**Comment by twskj** [comment]
From a quick check I see it show up in Instragram example.
Do you have a sample schema for this case?
![image](https://cloud.githubusercontent.com/assets/25628219/23168783/0043fb80-f80f-11e6-9790-7d48bf3a9920.png)

**Comment by twskj** [comment]
never mind I found it. confirmed it's a bug

**Comment by cristianbojor** [comment]
Sorry for not explaining better, i was in a hurry. For further references i will add this.

On Swagger Editor you can see the description on user_name:
![screenshot from 2017-02-21 16 36 25](https://cloud.githubusercontent.com/assets/9370914/23169506/a64c1fa4-f854-11e6-9b45-02527162b6c0.png)

But on the generated html with pretty-swag it does not appear:
![screenshot from 2017-02-21 16 39 45](https://cloud.githubusercontent.com/assets/9370914/23169532/c3fde55a-f854-11e6-92c4-7a0628815956.png)

**Comment by cristianbojor** [comment]
Great work anyway! Exactly what I need

**Comment by twskj** [comment]
WIP

**Comment by cristianbojor** [comment]
Wrong click :D

**Comment by twskj** [comment]
rolled out :-)
