### ISSUE TITLE
The navigation feels broken

### ISSUE THREAD

**Issue by Maaartinus** [twskj/pretty-swag#54]
I was told, that the cross shown when you click in the `#search` input was expected to clear the search. Instead it closes the editing, which feels like broken. Note that closing can be done simply by clicking somewhere else. WDYT?

**Comment by twskj** [comment]
It is meant to be a close button, but your argument is very sound.
The other side of the argument would be: We can simply `Ctrl+A` / `Cmd+A` and `Del` too.

But I do see the benefit of it. I'll look into this after.
Thanks for your suggestion

**Comment by twskj** [comment]
previously added
