### ISSUE TITLE
SyntaxError: Unexpected token s in JSON at position 0

### ISSUE THREAD

**Issue by rfbryan** [twskj/pretty-swag#56]
It appears that, starting with 0.1.150 the input file is always being treated as JSON.  My input file is yaml, and when passed into pretty-swag I get this:

Format:  singleFile
MarkDown:  Disable
Nav Bar:  Fixed
Auto tags:  Enable
Initial Collapse [Path: false, Method: false, Tool :true]
Theme: blue
No Credit
Error: SyntaxError: Unexpected token s in JSON at position 0
[ERROR] Command execution failed.

(note, that my yaml input file starts with 's')

**Comment by twskj** [comment]
Thanks for reporting. I'll look into this shortly.

**Comment by twskj** [comment]
I roll out a patch on `0.1.154`. Test it out and let me know 👍

**Comment by rfbryan** [comment]
Yep!  Works like a charm.  Thanks!
