### ISSUE TITLE
does not render bullets in the description when passed markdown flag

### ISSUE THREAD

**Issue by salarkhan** [twskj/pretty-swag#60]
``` // LocationCreate allows a developer to create an Location.
  //
  // __Possible Errors:__
  //    * 400: PARSE_ERROR
  //    * 500: INTERNAL_SERVER_ERROR
  rpc LocationCreate (CreateLocationRequest) returns (CreateLocationResponse){
    option (google.api.http) = {
      post: "/developers/{developer_id}/accounts/{account_id}/locations"
      body: "*"
    };
  }
```

results in this:
<img width="676" alt="screen shot 2019-02-01 at 11 15 45 am" src="https://user-images.githubusercontent.com/3118416/52144319-c6e9f900-2612-11e9-8faf-3256c0ebb174.png">

**Comment by twskj** [comment]
Turned out it's a default style for this material CSS that I use.
But, you can overwrite it easily by adding your CSS in a configuration file.

config.json
```json
{
    "customCSS": "ul:not(.browser-default) li{list-style-type:circle;margin-left:2em}"
}
```

and calling `pretty-swag` like you normally would with `-c` switch

`pretty-swag -i input.json -o output.html -m -c config.json`
