### ISSUE TITLE
Warnings when installing

### ISSUE THREAD

**Issue by 7ruth** [twskj/pretty-swag#61]
Me and my peers are seeing the following warnings when running:

``` npm install pretty-swag -g ```

![image](https://user-images.githubusercontent.com/10719152/53360141-c0455d80-3902-11e9-8fd7-8ce024a4a810.png)

**Comment by twskj** [comment]
One of its dependencies need to be updated. I'll patch it this evening.
Thanks for reporting.

**Comment by 7ruth** [comment]
Thank you for updating and maintaining this tool!

**Comment by twskj** [comment]
No problem. Turned out those warnings are from `highlight.js` which can be tracked here: https://github.com/highlightjs/highlight.js/issues/1369

**Comment by twskj** [comment]
v0.2.2 should not have these complains anymore
