### ISSUE TITLE
Error: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by fredplourde** [twskj/pretty-swag#65]
Hi

When updating from  0.1.144 we are getting"  Error: TypeError: Cannot read property 'length' of undefined" when generating the pretty-swag html

Any reason why?

Thanks

**Comment by twskj** [comment]
I could help troubleshoot that but my first initial thought is that it missing some required keys.
If you can post the json here, it make it easier to troubleshoot.

**Comment by fredplourde** [comment]
Hi here is the .json

[oct-tau-ecm-api.zip](https://github.com/twskj/pretty-swag/files/3531742/oct-tau-ecm-api.zip)

Which required keys?

Thanks

**Comment by twskj** [comment]
`schemes` is missing from the file.
Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by fredplourde** [comment]
Thanks I added a http schemes and it works.  One small issue though the "Try This Operation" button is gone from the .html do you know why?

**Comment by twskj** [comment]
Your schema is missing `host`

**Comment by fredplourde** [comment]
Thanks I got it.
Close this since there is no bug here 👍
