### ISSUE TITLE
Feature request: Json prettifier

### ISSUE THREAD

**Issue by bark** [twskj/pretty-swag#7]
It could be nice that you can chose to use json prettifier on the Response Body.
Some thing like:
https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?utm_source=chrome-app-launcher-info-dialog

**Comment by twskj** [comment]
I just checked I did indent the json result.
By prettier you mean syntax highlighter?

**Comment by bark** [comment]
i mean syntax highlighter and ability to fold part if the json you are not interested in.

**Comment by tejasbubane** [comment]
> i mean syntax highlighter and ability to fold part if the json you are not interested in.

I can already see the ability to fold part of json (by clickling on opening braces). Syntax highlighter would be a good addition 👍 .

**Comment by twskj** [comment]
Rolled out on V. 0.1.115
Use preview button to show JSON viewer.

![image](https://user-images.githubusercontent.com/25628219/28742539-114f113e-73f8-11e7-8d5e-2baf0a002203.png)
