### ISSUE TITLE
option to remove "generated" date from output

### ISSUE THREAD

**Issue by tmulry** [twskj/pretty-swag#8]
Could you add an flag to prevent the date from displaying in the footer?  For version control reasons, I would like to be able to run the generator repeatedly(like on each commit) and not have the output file update unless the corresponding yaml has changed.  `<footer class="container grey-text text-lighten-4 thin">Generated Monday, Mar 6, 2017, 12:15 PM by <a href="https://github.com/twskj/pretty-swag">pretty-swag</a></footer>`

**Comment by twskj** [comment]
no prob

**Comment by twskj** [comment]
rolled out

use 
`-noDate` to removeDate
`-noCredit` to removeCredit
