### ISSUE TITLE
Bug: don't understand $ref in path.

### ISSUE THREAD

**Issue by bark** [twskj/pretty-swag#9]
```
{
    "swagger": "2.0",
     ...
    "paths": {
      	"/test": {
      	   "$ref": "./endpoints/test.json"
      	}
    }
}
```
this should give me a endpoint named /test and all information in test.json. but it give: 
![image](https://cloud.githubusercontent.com/assets/223964/23752975/e40fef52-04d7-11e7-822e-6c3c868216a9.png)

Walk around for more people having this problem is to use the cli tool json-refs before.

**Comment by twskj** [comment]
Quite amount of code need to be added.
But I'll be working on it this weekend :-)

**Comment by twskj** [comment]
rolled out as version .71. Can you check please.

**Comment by bark** [comment]
Yes that works good, Nice! thanks :)
